name: update endorsements

on:
  workflow_dispatch:
    # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: franzdiebold/github-env-vars-action@v2.1.0
        # https://github.com/marketplace/actions/github-environment-variables-action
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run endorse --if-present
        env:
          ENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

